// <auto-generated />
using System;
using Medialuncita.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Medialuncita.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MedialuncitaDbContext))]
    [Migration("20260829000231_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Medialuncita.Domain.Entities.ConfiguracionGlobal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstrategiaPrecioDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstrategiaRedondeoDefault")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MargenPorcentualDefault")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MultiplicadorDefault")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TarifaManoDeObraPorHora")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionGlobal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstrategiaPrecioDefault = 1,
                            EstrategiaRedondeoDefault = 0,
                            MargenPorcentualDefault = 0m,
                            MultiplicadorDefault = 1m,
                            TarifaManoDeObraPorHora = 0m
                        });
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.HistorialPrecioIngrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnidadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnidadId");

                    b.HasIndex("IngredienteId", "Fecha");

                    b.ToTable("HistorialPreciosIngredientes");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.HistorialPrecioMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnidadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnidadId");

                    b.HasIndex("MaterialId", "Fecha");

                    b.ToTable("HistorialPreciosMateriales");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DensidadGramosPorMililitro")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MermaDefault")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnidadCompraId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.HasIndex("UnidadCompraId");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MermaDefault")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnidadCompraId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnidadCompraId");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.Presupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteNombre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.PresupuestoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoIngredientesSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoManoDeObraSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoPackagingSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoServiciosSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoTotalSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostoUnitarioSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("EstrategiaPrecioSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstrategiaRedondeoSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MargenPorcentualSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MultiplicadorSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreProductoSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreVarianteSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitarioAlMomento")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("PresupuestoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductoVarianteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TarifaManoDeObraPorHoraSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("TiempoTotalMinutosSnapshot")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PresupuestoId");

                    b.ToTable("PresupuestoItems");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.PresupuestoItemIngredienteDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CantidadEfectivaSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CantidadRequeridaSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MermaAplicadaSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreIngredienteSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitarioUsadoSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("PresupuestoItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubtotalSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PresupuestoItemId");

                    b.ToTable("PresupuestoItemIngredienteDetalles");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.PresupuestoItemMaterialDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CantidadEfectivaSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CantidadRequeridaSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MermaAplicadaSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreMaterialSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioUnitarioUsadoSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("PresupuestoItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubtotalSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PresupuestoItemId");

                    b.ToTable("PresupuestoItemMaterialDetalles");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.PresupuestoItemServicioDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModoProrrateoSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreServicioSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PresupuestoItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubtotalSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PresupuestoItemId");

                    b.ToTable("PresupuestoItemServicioDetalles");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecetaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecetaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.ProductoVariante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstrategiaPrecioOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstrategiaRedondeoOverride")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MargenPorcentualOverride")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MultiplicadorOverride")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrecioManualOverride")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RendimientoCantidad")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("RendimientoUnidadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TiempoAdicionalPorLoteMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TiempoAdicionalPorUnidadMinutos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("RendimientoUnidadId");

                    b.ToTable("ProductoVariantes");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.Receta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RendimientoBaseCantidad")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("RendimientoBaseUnidadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TiempoPreparacionBaseMinutos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RendimientoBaseUnidadId");

                    b.ToTable("Recetas");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.RecetaIngrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MermaOverride")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecetaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnidadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("RecetaId");

                    b.HasIndex("UnidadId");

                    b.ToTable("RecetaIngredientes");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.RecetaServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModoProrrateo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecetaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServicioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecetaId");

                    b.HasIndex("ServicioId");

                    b.ToTable("RecetaServicios");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CostoPorHora")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CostoPorLote")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FactorAUnidadBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.VarianteIngredienteOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CantidadOverride")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnidadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VarianteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("UnidadId");

                    b.HasIndex("VarianteId");

                    b.ToTable("VarianteIngredienteOverrides");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.VarianteMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VarianteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("VarianteId");

                    b.ToTable("VarianteMateriales");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.VarianteServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModoProrrateo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServicioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VarianteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServicioId");

                    b.HasIndex("VarianteId");

                    b.ToTable("VarianteServicios");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.HistorialPrecioIngrediente", b =>
                {
                    b.HasOne("Medialuncita.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany("HistorialPrecios")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medialuncita.Domain.Entities.UnidadMedida", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.HistorialPrecioMaterial", b =>
                {
                    b.HasOne("Medialuncita.Domain.Entities.Material", "Material")
                        .WithMany("HistorialPrecios")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medialuncita.Domain.Entities.UnidadMedida", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.Ingrediente", b =>
                {
                    b.HasOne("Medialuncita.Domain.Entities.UnidadMedida", "UnidadCompra")
                        .WithMany()
                        .HasForeignKey("UnidadCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadCompra");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.Material", b =>
                {
                    b.HasOne("Medialuncita.Domain.Entities.UnidadMedida", "UnidadCompra")
                        .WithMany()
                        .HasForeignKey("UnidadCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadCompra");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.PresupuestoItem", b =>
                {
                    b.HasOne("Medialuncita.Domain.Entities.Presupuesto", "Presupuesto")
                        .WithMany("Items")
                        .HasForeignKey("PresupuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presupuesto");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.PresupuestoItemIngredienteDetalle", b =>
                {
                    b.HasOne("Medialuncita.Domain.Entities.PresupuestoItem", "PresupuestoItem")
                        .WithMany("DetalleIngredientes")
                        .HasForeignKey("PresupuestoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PresupuestoItem");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.PresupuestoItemMaterialDetalle", b =>
                {
                    b.HasOne("Medialuncita.Domain.Entities.PresupuestoItem", "PresupuestoItem")
                        .WithMany("DetalleMateriales")
                        .HasForeignKey("PresupuestoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PresupuestoItem");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.PresupuestoItemServicioDetalle", b =>
                {
                    b.HasOne("Medialuncita.Domain.Entities.PresupuestoItem", "PresupuestoItem")
                        .WithMany("DetalleServicios")
                        .HasForeignKey("PresupuestoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PresupuestoItem");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.Producto", b =>
                {
                    b.HasOne("Medialuncita.Domain.Entities.Receta", "Receta")
                        .WithMany()
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.ProductoVariante", b =>
                {
                    b.HasOne("Medialuncita.Domain.Entities.Producto", "Producto")
                        .WithMany("Variantes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medialuncita.Domain.Entities.UnidadMedida", "RendimientoUnidad")
                        .WithMany()
                        .HasForeignKey("RendimientoUnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("RendimientoUnidad");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.Receta", b =>
                {
                    b.HasOne("Medialuncita.Domain.Entities.UnidadMedida", "RendimientoBaseUnidad")
                        .WithMany()
                        .HasForeignKey("RendimientoBaseUnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RendimientoBaseUnidad");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.RecetaIngrediente", b =>
                {
                    b.HasOne("Medialuncita.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Medialuncita.Domain.Entities.Receta", "Receta")
                        .WithMany("Ingredientes")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medialuncita.Domain.Entities.UnidadMedida", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Receta");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.RecetaServicio", b =>
                {
                    b.HasOne("Medialuncita.Domain.Entities.Receta", "Receta")
                        .WithMany("Servicios")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medialuncita.Domain.Entities.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receta");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.VarianteIngredienteOverride", b =>
                {
                    b.HasOne("Medialuncita.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Medialuncita.Domain.Entities.UnidadMedida", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Medialuncita.Domain.Entities.ProductoVariante", "Variante")
                        .WithMany("IngredienteOverrides")
                        .HasForeignKey("VarianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Unidad");

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.VarianteMaterial", b =>
                {
                    b.HasOne("Medialuncita.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Medialuncita.Domain.Entities.ProductoVariante", "Variante")
                        .WithMany("Materiales")
                        .HasForeignKey("VarianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.VarianteServicio", b =>
                {
                    b.HasOne("Medialuncita.Domain.Entities.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Medialuncita.Domain.Entities.ProductoVariante", "Variante")
                        .WithMany("Servicios")
                        .HasForeignKey("VarianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicio");

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.Ingrediente", b =>
                {
                    b.Navigation("HistorialPrecios");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.Material", b =>
                {
                    b.Navigation("HistorialPrecios");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.Presupuesto", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.PresupuestoItem", b =>
                {
                    b.Navigation("DetalleIngredientes");

                    b.Navigation("DetalleMateriales");

                    b.Navigation("DetalleServicios");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.ProductoVariante", b =>
                {
                    b.Navigation("IngredienteOverrides");

                    b.Navigation("Materiales");

                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("Medialuncita.Domain.Entities.Receta", b =>
                {
                    b.Navigation("Ingredientes");

                    b.Navigation("Servicios");
                });
#pragma warning restore 612, 618
        }
    }
}
